// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service structure for project-related operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Load the global configuration. This configuration determines what the Rclone remotes
 * are, and where their corresponding local project folders are found.
 * @returns {Promise<$models.GlobalConfig> & { cancel(): void }}
 */
export function LoadGlobalConfig() {
    let $resultPromise = /** @type {any} */($Call.ByID(1686438339));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Navigate to the specified project directory and find the sync.json config file. If it is not found,
 * create a blank one.
 * @param {string} selectedProject
 * @returns {Promise<string> & { cancel(): void }}
 */
export function LoadProjectConfig(selectedProject) {
    let $resultPromise = /** @type {any} */($Call.ByID(2892494869, selectedProject));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.GlobalConfig.createFrom;
