// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Open the requested folder in the user's file explorer
 */
export function OpenFolder(targetFolder: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2474413535, targetFolder) as any;
    return $resultPromise;
}
