// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Wrapper function for creating folders
 */
export function CreateLocalFolders(targetFolders: string[]): $CancellablePromise<void> {
    return $Call.ByID(1403706680, targetFolders);
}

/**
 * Wrapper function for deleting folders
 */
export function DeleteLocalFolders(targetFolders: string[]): $CancellablePromise<void> {
    return $Call.ByID(1155014579, targetFolders);
}

/**
 * Given a target folder, scrub it out of the project configuration's folders. This does NOT delete the folder
 * locally nor remotely. It only untracks it. Full deletions should be carefully handled manually with Rclone
 * for now.
 */
export function DeregisterFolder(targetFolder: string): $CancellablePromise<$models.ProjectConfig> {
    return $Call.ByID(1475157726, targetFolder).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Given an existing folder, a new folder name, and a new FolderConfig, update the existing folder to match the new items.
 * Return the entire ProjectConfig after, which will contain the fully updated map of Folders.
 */
export function EditFolder(currentFolderName: string, newFolderName: string, newFolderConfig: $models.FolderConfig): $CancellablePromise<$models.ProjectConfig> {
    return $Call.ByID(1535184624, currentFolderName, newFolderName, newFolderConfig).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLocalFolders checks if the local paths for all folders in the ProjectConfig exist.
 * Returns a list of folder keys where the paths exist, or an error if something goes wrong.
 */
export function GetLocalFolders(): $CancellablePromise<string[]> {
    return $Call.ByID(1746980032).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Open the requested folder in the user's file explorer
 */
export function OpenFolder(targetFolder: string): $CancellablePromise<void> {
    return $Call.ByID(3234094764, targetFolder);
}

/**
 * OpenFolderPicker opens a native OS folder selection dialog and returns the selected path.
 * The returned path is relative to the project root. Returns an empty string if cancelled.
 */
export function OpenFolderPicker(): $CancellablePromise<string> {
    return $Call.ByID(1001267190);
}

/**
 * Given a new folder name and a new FolderConfig, create a new FolderConfig for it in the ProjectConfig.
 * Return the entire ProjectConfig after, which will contain the fully updated map of Folders.
 */
export function RegisterNewFolder(newFolderName: string, folderConfig: $models.FolderConfig): $CancellablePromise<$models.ProjectConfig> {
    return $Call.ByID(1863241101, newFolderName, folderConfig).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProjectConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
