// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Wrapper function for creating folders
 */
export function CreateLocalFolders(targetFolders: string[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1403706680, targetFolders) as any;
    return $resultPromise;
}

/**
 * Wrapper function for deleting folders
 */
export function DeleteLocalFolders(targetFolders: string[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1155014579, targetFolders) as any;
    return $resultPromise;
}

/**
 * GetLocalFolders checks if the local paths for all folders in the ProjectConfig exist.
 * Returns a list of folder keys where the paths exist, or an error if something goes wrong.
 */
export function GetLocalFolders(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1746980032) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Open the requested folder in the user's file explorer
 */
export function OpenFolder(targetFolder: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3234094764, targetFolder) as any;
    return $resultPromise;
}

export function RegisterNewFolder(newFolderName: string, folderConfig: $models.FolderConfig): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1863241101, newFolderName, folderConfig) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
