// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadGlobalConfig ensures the configuration is loaded.
 * @param {string} selectedProject
 * @returns {Promise<$models.ProjectConfig> & { cancel(): void }}
 */
export function LoadProjectConfig(selectedProject) {
    let $resultPromise = /** @type {any} */($Call.ByID(875278892, selectedProject));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ProjectConfig.createFrom;
