// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const RcloneAction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PUSH: "PUSH",
    PULL: "PULL",
    COPY_TO: "COPY_TO",
    COPY_FROM: "COPY_FROM",
};
