// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} targetFolder
 * @param {$models.RcloneAction} action
 * @returns {Promise<string> & { cancel(): void }}
 */
export function ExecuteRcloneAction(targetFolder, action) {
    let $resultPromise = /** @type {any} */($Call.ByID(1430199943, targetFolder, action));
    return $resultPromise;
}
