// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Detect which of the given local folders have any updates. This is a naive check, as it does no checks on modified time to see
 * whether the changes are local or upstream. It's up to the user to be careful.
 * TODO: Flesh this check out, possibly using "rclone check", especially in cases where multiple users are working on the project at once.
 */
export function DetectChangedFolders(localFolders: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2751813025, localFolders).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * This function performs the full backup to the specified location for the configured remote.
 */
export function ExecuteFullBackup(dry: boolean): $CancellablePromise<$models.RcloneActionOutput[]> {
    return $Call.ByID(1373287177, dry).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Error handling is done per request, and gracefully returned to the user for evaluation in the frontend.
 */
export function ExecuteRcloneAction(targetFolders: string[], action: $models.RcloneAction, dry: boolean): $CancellablePromise<$models.RcloneActionOutput[]> {
    return $Call.ByID(1430199943, targetFolders, action, dry).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.RcloneActionOutput.createFrom;
const $$createType2 = $Create.Array($$createType1);
