// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Detect which of the given local folders have any updates. This is a naive check, as it does no checks on modified time to see
 * whether the changes are local or upstream. It's up to the user to be careful.
 * TODO: Flesh this check out, possibly using "rclone check", especially in cases where multiple users are working on the project at once.
 */
export function DetectChangedFolders(localFolders: string[]): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2751813025, localFolders) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DetectChangedFoldersAsync runs change detection in parallel, emitting per-folder events.
 * Emits "detect-folder-complete" for each folder and "detect-complete" when all done.
 */
export function DetectChangedFoldersAsync(taskID: string, localFolders: string[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(808215963, taskID, localFolders) as any;
    return $resultPromise;
}

/**
 * This function performs the full backup to the specified location for the configured remote.
 */
export function ExecuteFullBackup(dry: boolean): Promise<$models.RcloneActionOutput[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1373287177, dry) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ExecuteFullBackupAsync runs the full backup in a background goroutine,
 * emitting events as the operation completes.
 */
export function ExecuteFullBackupAsync(taskID: string, dry: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2263277875, taskID, dry) as any;
    return $resultPromise;
}

/**
 * Error handling is done per request, and gracefully returned to the user for evaluation in the frontend.
 */
export function ExecuteRcloneAction(targetFolders: string[], action: $models.RcloneAction, dry: boolean): Promise<$models.RcloneActionOutput[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1430199943, targetFolders, action, dry) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ExecuteRcloneActionAsync runs the rclone action for each folder in parallel,
 * emitting a "task-folder-complete" event as each folder finishes.
 * When all folders are done, emits a "task-complete" event.
 * Returns immediately; the taskID correlates events to the original request.
 */
export function ExecuteRcloneActionAsync(taskID: string, targetFolders: string[], action: $models.RcloneAction, dry: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1463246281, taskID, targetFolders, action, dry) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.RcloneActionOutput.createFrom;
const $$createType2 = $Create.Array($$createType1);
